[package]
name = "test-web-hopper"
authors = ["David Weis <dweis7@gmail.com>"]
description = ""
edition = "2021"
license = "MIT OR APACHE"
publish = false
readme = "README.md"
repository = "https://github.com/dmweis/hopper-web"
version = "0.1.0"

[dependencies]
bevy = "0.12"
bevy_stl = "0.12.0"
