[package]
authors = ["David Weis <dweis7@gmail.com>"]
description = ""
edition = "2021"
license = "MIT OR APACHE"
name = "test-web-hopper"
publish = false
readme = "README.md"
repository = "https://github.com/dmweis/NONE"
version = "0.1.0"

[dependencies]
bevy = "0.12.1"
